### ISSUE TITLE
Error running pipeline.py

### ISSUE THREAD

**Issue by mmichaelzhang** [YangLin-George/PLELog#3]
Hi,

I am facing trouble running pipeline.py, and it shows error logs below:

python pipeline.py --dataset HDFS
/home/dsi/shezhang/.local/lib/python3.8/site-packages/sklearn/decomposition/_fastica.py:116: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn(
pipeline.py:194: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  predicts = estimator.fit_predict(np.asarray(trainReprs, dtype=np.float)).tolist()
Traceback (most recent call last):
  File "/home/dsi/shezhang/.local/lib/python3.8/site-packages/joblib/parallel.py", line 822, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
  File "/home/dsi/shezhang/Download/Python-3.8.3/Lib/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pipeline.py", line 373, in <module>
    result = main_process(save_path=save_path, pre_train=pre_train, pre_dev=pre_dev, pre_test=pre_test, ratios=ratios,
  File "pipeline.py", line 248, in main_process
    train, dev, test, precision, recall, f, num_of_neg1, num_outlier0 = PULearn(pre_train, pre_dev, pre_test,
  File "pipeline.py", line 194, in PULearn
    predicts = estimator.fit_predict(np.asarray(trainReprs, dtype=np.float)).tolist()
  File "/home/dsi/shezhang/.local/lib/python3.8/site-packages/hdbscan/hdbscan_.py", line 941, in fit_predict
    self.fit(X)
  File "/home/dsi/shezhang/.local/lib/python3.8/site-packages/hdbscan/hdbscan_.py", line 919, in fit
    self._min_spanning_tree) = hdbscan(X, **kwargs)
  File "/home/dsi/shezhang/.local/lib/python3.8/site-packages/hdbscan/hdbscan_.py", line 610, in hdbscan
    (single_linkage_tree, result_min_span_tree) = memory.cache(
  File "/home/dsi/shezhang/.local/lib/python3.8/site-packages/joblib/memory.py", line 349, in __call__
    return self.func(*args, **kwargs)
  File "/home/dsi/shezhang/.local/lib/python3.8/site-packages/hdbscan/hdbscan_.py", line 275, in _hdbscan_boruvka_kdtree
    alg = KDTreeBoruvkaAlgorithm(tree, min_samples, metric=metric,
  File "hdbscan/_hdbscan_boruvka.pyx", line 375, in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm.__init__
  File "hdbscan/_hdbscan_boruvka.pyx", line 411, in hdbscan._hdbscan_boruvka.KDTreeBoruvkaAlgorithm._compute_bounds
  File "/home/dsi/shezhang/.local/lib/python3.8/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/dsi/shezhang/.local/lib/python3.8/site-packages/joblib/parallel.py", line 833, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
  File "hdbscan/_hdbscan_boruvka.pyx", line 412, in genexpr
TypeError: delayed() got an unexpected keyword argument 'check_pickle'

**Comment by YangLin-George** [comment]
New version of PLELog has been uploaded, environment issues have been carefully taken care of.
Thanks for your comment. If anything goes wrong, please let me know.
